use convert_case::{Case, Casing};
use strum_macros::EnumIter;

use super::utils::*;

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, EnumIter)]
pub enum Gender {
    Male,
    Female,
}

static_gen_fn_all!(Gender);

impl std::fmt::Display for Gender {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", format!("{self:?}").to_case(Case::Lower))
    }
}

pub fn reasons_to_adventure() -> &'static [&'static str] {
    static RETVAL: [&'static str; 20] = [
        "you could't stand your tedious and repetitive existence.",
        "you want to learn more about the world.",
        "being on the road will keep you away from your past.",
        "you answered the calling of the Church.",
        "you want to make the world a better place.",
        "you want minstrels to tell your tale for centuries to come.",
        "you seek redemption from your sins.",
        "you want money, more than many could earn in a lifetime.",
        "you were extremely bad at your past occupation.",
        "you seek vengeance on someone who ruined your life.",
        "you want to follow in the footsteps of one of your relatives.",
        "you think you would make a decent adventurer.",
        "you seek the thrill of adventure.",
        "you want to improve yourself.",
        "you want to prove you can handle yourself.",
        "you have a duty to uphold.",
        "you seek a honourable death.",
        "you have lost everything and want to start over.",
        "you want to save the Kingdom.",
        "events out of your control forced you to.",
    ];
    &RETVAL
}

pub fn appearances() -> &'static [&'static str] {
    static RETVAL: [&'static str; 40] = [
        "Quite short, you get mad when someone points it.",
        "Very tall, you often bump your head.",
        "Worryingly thin, almost emaciated.",
        "Corpulent, your belly shakes when you laugh.",
        "Ugly, but confident.",
        "Good looking, hopelessly vain.",
        "Filthy, your stench fills the room.",
        "Very clean, you try to wash yourself every day.",
        "Rotten teeth, bad breath.",
        "Beautiful teeth, constantly smiling.",
        "Plain features, your face is hard to remember.",
        "Exotic features, your ancestors hail from a distant land.",
        "Conventional clothing, you feel the need to conform.",
        "Unorthodox clothing, in a foreign fashion.",
        "Bad posture, slouching and hunching.",
        "Perfect posture, straight and proud.",
        "Glabrous, not a single hair grows on your body or face.",
        "Very hairy, they call you '`the Bear`'.",
        "Perfect diction, no accent.",
        "Strong accent, people struggle to understand you.",
        "Rough skin, callous and scarred.",
        "Oily skin, punctuated with boils and pustules.",
        "Perfect skin, smooth as silk.",
        "Large birthmark, surely proof you are of noble blood.",
        "Large tattoo, it represents something important to you.",
        "Numerous piercings, your face looks like a jewellery store.",
        "Bald, either by choice or by necessity.",
        "Long and luscious hair, your pride and joy.",
        "Dyed hair, in an unusual colour.",
        "Unusual hairstyle, sure to attract attention.",
        "Pox scars, all over your body and face.",
        "Blade scar, you lost a fight but were spared.",
        "Claw scar, you have nightmares about it.",
        "Burn scar, your home was once put to the torch.",
        "Noose scar, you escaped the gallows.",
        "Ritual scars, self inflicted.",
        "Missing finger, memory of a past misadventure.",
        "Missing toe, you walk with a slight limp.",
        "Missing ear, a punishment for a past deed.",
        "Missing tooth, lost in a brawl.",
    ];
    &RETVAL
}

pub fn personalities() -> &'static [&'static str] {
    static RETVAL: [&'static str; 40] = [
        "Arrogant, you think you are always right.",
        "Humble, you don't give yourself enough credit.",
        "Craven, you sweat profusely when afraid.",
        "Brave, you are convinced you can't be defeated.",
        "Cautious, you are never at the front when danger lurks.",
        "Impulsive, you have barely escaped death more than once.",
        "Decadent, you can't resist wordly pleasures.",
        "Stoic, you refuse any form of luxury.",
        "Misanthrope, you have no qualms hurting fellow humans.",
        "Altruist, you can't help but look after others.",
        "Solitary, you only feel at ease by yourself.",
        "Sociable, sometimes you tell too much.",
        "Deceitful, you lie almost by reflex.",
        "Honest, at least more honest than most.",
        "Lazy, you hate to be disturbed when taking a break.",
        "Energetic, you can't stand still and quiet.",
        "Condescending, everyone is dumber than you.",
        "Respectful, you try to avoid conflict when possible.",
        "Competitive, you throw a tantrum when you lose.",
        "Apathetic, you just go through the motions.",
        "Submissive, it's easier to just follow others.",
        "Bossy, you constantly order people around.",
        "Superstitious, you hoard useless trinkets.",
        "Sceptical, it's hard to convince you.",
        "Naive, you are convinced there is good in everyone.",
        "Experienced, you have learnt from past misadventures.",
        "Wicked, nothing is wrong as long as it brings you benefit.",
        "Righteous, you can't stand to see a wrong go unpunished.",
        "Irreverent, constantly badmouthing the authorities.",
        "Pious, you mutter a prayer before tackling challenge.",
        "Sarcastic, you are the only one who laughs at your jokes.",
        "Stern, nobody remembers seeing you smiling.",
        "Reserved, the less people know about you the better.",
        "Braggart, always talking loudly about your exploits.",
        "Tactful, sometimes almost too subtle.",
        "Blunt, you just say what you think.",
        "Silent, you only say what's essential.",
        "Chatty, you can talk for hours without interruption.",
        "Pragmatic, the end result is all that matters.",
        "Idealistic, you have principles and stand by them.",
    ];
    &RETVAL
}

pub fn masculine_first_names() -> &'static [&'static str] {
    static MALE_NAMES: [&'static str; 80] = [
        "Adalbert",
        "Allwin",
        "Alard",
        "Aaldred",
        "Alexander",
        "Alured",
        "Amaury",
        "Amairic",
        "Anselm",
        "Arnald",
        "Baldric",
        "Baldwin",
        "Balthasar",
        "Bertram",
        "Blackwin",
        "Colin",
        "Constantine",
        "David",
        "Edwin",
        "Elias",
        "Helyas",
        "Engeram",
        "Ernald",
        "Eustace",
        "Fabian",
        "Fordwin",
        "Fulk",
        "Gamel",
        "Geoffrey",
        "Gerard",
        "Gervase",
        "Gilbert",
        "Giles",
        "Gladwin",
        "Godwin",
        "Grimald",
        "Guy",
        "Hamo",
        "Hamond",
        "Harding",
        "Henry",
        "Herlewin",
        "Hervey",
        "Hugh",
        "James",
        "Jocelin",
        "John",
        "Lawrence",
        "Leofwin",
        "Martin",
        "Maurice",
        "Meginhard",
        "Michael",
        "Nigel",
        "Norman",
        "Nicholas",
        "Odo",
        "Osbert",
        "Peter",
        "Pippin",
        "Philip",
        "Ralf",
        "Ranulf",
        "Richard",
        "Robert",
        "Samer",
        "Savaric",
        "Simon",
        "Stephan",
        "Terric",
        "Theobald",
        "Thomas",
        "Thurstan",
        "Umfrey",
        "Waleran",
        "Warin",
        "Werinbert",
        "William",
        "Wilmarc",
        "Ymbert",
    ];
    &MALE_NAMES
}

pub fn feminine_first_names() -> &'static [&'static str] {
    static FEMALE_NAMES: [&'static str; 80] = [
        "Ada",
        "Adallinda",
        "Adaltrude",
        "Agnes",
        "Albreda",
        "Aldith",
        "Aldusa",
        "Alice",
        "Alina",
        "Amanda",
        "Amiria",
        "Annabel",
        "Annora",
        "Avelina",
        "Avice",
        "Beatrice",
        "Basilea",
        "Bela",
        "Berta",
        "Bertrada",
        "Carlotta",
        "Celestria",
        "Cecilia",
        "Clarice",
        "Constance",
        "Desdemona",
        "Dionisia",
        "Edith",
        "Eleanor",
        "Elizabeth",
        "Estrilda",
        "Isabel",
        "Felicia",
        "Fina",
        "Gersvinda",
        "Gisela",
        "Golda",
        "Gundred",
        "Haunild",
        "Hawisa",
        "Helena",
        "Helewise",
        "Hildegarde",
        "Ida",
        "Ingrid",
        "Ireena",
        "Isolda",
        "Joan",
        "Juliana",
        "Katherine",
        "Laetitia",
        "Liecia",
        "Linota",
        "Lora",
        "Lucretia",
        "Lucia",
        "Mabel",
        "Malota",
        "Margaret",
        "Margery",
        "Marsilia",
        "Mary",
        "Mathilda",
        "Mazelina",
        "Millicent",
        "Muriel",
        "Nesta",
        "Ophelia",
        "Philippa",
        "Petronilla",
        "Primeveire",
        "Richenda",
        "Roesia",
        "Rothaide",
        "Sabina",
        "Sarah",
        "Serena",
        "Susanna",
        "Sybilla",
        "Theodelinda",
    ];
    &FEMALE_NAMES
}

pub fn first_names(gender: Gender) -> &'static [&'static str] {
    match gender {
        Gender::Male => masculine_first_names(),
        Gender::Female => feminine_first_names(),
    }
}

pub fn last_names() -> &'static [&'static str] {
    static RETVAL: [&'static str; 80] = [
        "Albon",
        "Alder",
        "Applebottom",
        "Atterberry",
        "Ayers",
        "Barnes",
        "Bigelow",
        "Blacklock",
        "Charker",
        "Coppard",
        "Crask",
        "Crathorne",
        "Daintith",
        "Deane",
        "Dodd",
        "Duguid",
        "Easterbrook",
        "Elwood",
        "Fairclough",
        "Fayne",
        "Fitt",
        "Freeman",
        "Goodacre",
        "Gorsuch",
        "Gowing",
        "Graves",
        "Griswold",
        "Grosseteste",
        "Hackett",
        "Hawthorne",
        "Hogben",
        "Holdman",
        "Holmes",
        "Horscroft",
        "Inglett",
        "Jepson",
        "Kidner",
        "Knowles",
        "Laidler",
        "Laverick",
        "Limmer",
        "Luffman",
        "Mabey",
        "Marsh",
        "Mawdesley",
        "Millerchip",
        "Mincer",
        "Moore",
        "Mowell",
        "Muckle",
        "Myres",
        "Naldrett",
        "Nesmith",
        "Newby",
        "Nigh",
        "Nottage",
        "Odom",
        "Paine",
        "Palfrey",
        "Pedler",
        "Pettengill",
        "Pickerill",
        "Porteous",
        "Postle",
        "Provan",
        "Quinnel",
        "Rattue",
        "Reep",
        "Rountree",
        "Sadd",
        "Scroggs",
        "Sisley",
        "Smitherman",
        "Tamblyn",
        "Thew",
        "Thorburn",
        "Thurgood",
        "Waghorn",
        "Wanless",
        "Woods",
    ];
    &RETVAL
}

pub fn relationships() -> &'static [&'static str] {
    static RETVAL: [&'static str; 20] = [
        "met in prison, spent a few years there together.",
        "fought a war together, they share terrible memories.",
        "met in a tavern, made friends after a few drinks.",
        "served under the same person.",
        "have been travelling together. It's safer.",
        "are childhood friends, grew up together. Good memories.",
        "are relatives, they can't stand each other but they still care.",
        "have a common acquaintance who introduced them.",
        "studied under the same mentor.",
        "are the sole survivors of a previous company.",
        "are the sole survivors of a ravaged village.",
        "were accomplices in crime.",
        "are mentor and pupil.",
        "are master and servant.",
        "just met the other day, but get along surprisingly well.",
        "come from the same village, barely talked before.",
        "worked together before.",
        "come from two families with close ties.",
        "have witnessed something weird and incredible together.",
        "share a common secret, they don't talk about it.",
    ];
    &RETVAL
}
