== Introduction

=== Overview

_Murdham_ is a role-playing game of perilous adventures for 2 to 6 people.
One person acts as the Game Master (GM) and is responsible for running the game.
Everyone else is a Player, interpreting a member of a company of adventurers on a quest for gold and fame.

The game takes place in a fantasy world loosely based on late medieval Europe.
The protagonists are not powerful heroes but common folks and roguish adventurers facing untold perils in the slim hope of getting rich.
Magic, gods, and demons are real and dangerous, promising great power but at a terrible cost.
Monsters, mutants, and other vile creatures roam the wilderness, while cities are home to crime and intrigue.

=== Scenarios

The game is based on scenarios describing the locations, challenges, people, and monsters encountered by the adventurers.
It is possible to link multiple scenarios to form a long running campaign during which the characters can develop.

A scenario ends once the Players have accomplished their goals, have failed to do so, or have met their demise.
There aren't winners or losers: the game's main point is to tell a fun emergent story together, and sometimes defeat can be more interesting than triumph!

=== The GM

If you are the GM, you are responsible for getting familiar with the rules and preparing a scenario to play before the game starts.
You can write your own scenarios or use those created by others.

During play you are responsible for running the game, acting as an impartial referee.
You are the Players' eyes and ears, describing the world to them as vividly and completely as possible.
You also interpret all characters who aren't controlled by the Players, both friends and foes.
Finally you have the task of judging the outcome of the characters' actions, using these rules as a tool to support your decisions.

It is important to stress that you are not the Players' adversary, and you are playing neither with nor against them.
Your main goal is for everyone at the table, including yourself, to have fun telling an exciting story together!


=== The Players

If you are a Player, you are responsible for interpreting your character and keeping track of their state.
You should strive to portray your character as realistically as possible, acting as if you were in their shoes.

Your main task is to describe what your character intends to do after the GM describes the current situation.
You are free to think outside of the rules and attempt anything which would realistically make sense under the current circumstances: the GM will adjudicate what happens when it isn't covered in this rulebook.
Always think about how to use the environment, your skills, and your gear to gain an edge over the obstacles and foes you encounter!

You play cooperatively with the other Players, attempting to reach the goals of the scenario together.
It is also important to stress that the GM is not your enemy, even though they will often control your foes and place obstacles on your path.
The GM is there to run the game, creating interesting challenges that you can have fun solving together with the other Players!


=== Required materials

Everyone at the table needs paper, pencil, rubber, and a set of polyhedral dice including a 4‑sided die, a 6‑sided die, an 8‑sided die, a 10‑sided die, a 12‑sided die, and a 20‑sided die.

The game doesn't use an actual board or tokens.
All game information is instead written or drawn on paper.
This includes details about the characters, maps, positioning during combat, etc.

You can enhance your experience with additional components (character sheets, reference sheets, handouts, grids, miniatures, tokens, etc.) or even play online using digital tools.
All of this is optional and a matter of personal preference.
