---
title: Combat
weight: 140
prev: /docs/encounters
next: /docs/powers
---
:toc:

== Combat procedure

Time is tracked using rounds during combat.
A round is divided in the following phases:

. *Initiative phase*.
Randomly determine which faction has the initiative by rolling a die.
For example, roll a d2 if there are two factions.
On the first round, the faction which started the fight automatically has the initiative.

. *Action phase*.
The factions alternate taking turns with one character at a time, starting with the faction with the initiative.
Each character can only take turn once per round.
A faction can choose to pass instead of taking turn with a character, and if all factions pass consecutively the phase ends.
A faction who has already taken turn with all its characters can only pass.

. *Morale phase*.
Check if any faction must make a morale check (see <<_morale>>).


== Taking a turn

During their turn characters can _move_ by 2 zones, perform a _bonus action_, and perform a _main action_ or a second _bonus action_, in any order.
It is possible to split movement before and after taking actions.

Alternatively, characters can take their turn outside of the normal order to perform a _reaction_ in response to a specific trigger.


== Main actions

* *Sprint* to double movement distance.

* *Attack* an enemy.

* *Invoke* a sorcerous power.

* Attempt to *distract*, *intimidate*, or *taunt* an enemy.
The character must also narrate how they attempt to do so, and it must be something effective under the current circumstances.

* *Interact* with the environment.

* *Pick up* or *put down* something.
Dropping something is free, but the item might be damaged if fragile.


== Bonus actions

* *Equip* or *unequip* an item.
Swapping two items is two bonus actions.
Armour can't be changed during a fight.

* *Use a consumable item*, such as a _healing draught_, an _antidote_, or a dose of poison.

* *Say a few words*.


== Reactions

* *Counter* an attack.

* *Dodge* an attack.

* *Guard* a nearby ally.

* Perform an *opportunity attack*.


== Attacking

Attacking an enemy is a main action.
In normal situations, attacks hit and inflict damage to the target automatically.
Attacks made in challenging circumstances require passing a WIT save to hit.

Unarmed attacks inflict d4 impaired damage.
Armed attacks inflict damage depending on the weapon used.
The attacker may choose to voluntarily hold back an attack to inflict impaired damage.
If the attacker targets a nearby _incapacitated_ character, they may choose to deliver a final blow and kill them.

* *Melee attacks*.
Target a nearby character.
Hitting a target who is not visible requires passing a WIT save or the attack misses and inflicts no damage.

* *Ranged attacks*.
Target a visible character within the indicated range.
Hitting targets beyond half range or while moving requires passing a WIT save or the attack misses and inflicts no damage.
Targeting a character beyond half range while moving, or a character who is not visible, is not possible at all.

* *Indirect ranged attacks*.
Can be directed at targets which aren't directly visible and over obstacles, but can only target beyond half range.
A WIT save to hit is always required.
Attacking while moving isn't possible.


== Reacting to an attack

Targets of an attack may attempt to dodge or counter as a reaction.
The choice must be made before rolling for damage but after the WIT save to hit, if required.
Targets who are unaware of their attacker can't react.

* *Dodge*.
Make an AGI save, and on a pass the attack misses.

* *Counter*.
Perform a suitable attack against the attacker.
Both characters roll for damage at the same time.
Whoever suffers the most damage, after reductions, is hit first.
In case of a tie both characters are hit at the same time.
Attacks with multiple targets can only be countered by a single target.

A character who is nearby the target of an attack can react by guarding them.
They become the new target of the attack.
Since they have spent their reaction to guard, they can't normally counter or dodge.


== Opportunity attacks

Characters can make an opportunity attack as a reaction against nearby enemies moving out of their position.
The target's movement is interrupted and the attack is resolved, after which their turn resumes.

It isn't normally possible to react to an opportunity attack, since the target is already spending the turn to act, but some skills might give an opportunity to do so.


== Protection from attacks

* *Concealment* partially obscures vision to the target.
Damage is impaired.

* *Cover* offers physical protection.
The target's armour value is increased by 1 unless the attack is powerful enough to penetrate the cover.

* *Barriers* completely block attacks.
If a character peaks behind cover to attack, they can be still countered and the barrier only counts as cover.


== Blast attacks

Blast attacks hit a zone and target all characters in it and on its borders.

Melee blast attacks hit the attacker's zone and don't target the attacker themselves.
They can't miss.

Ranged blast attacks hit any zone within range and target the attacker as well if directed at their own zone.
If they miss, they are deviated and hit a random neighbouring zone.
You can assign a number to each neighbouring zone and roll a die to determine which one.


== Attack stunts

The attacker can propose an alternative effect to the target instead of inflicting damage (cutting a limb, forcing a surrender, etc.).
This must be done before the target decides whether to react but after the WIT save to hit, and the alternative effect must make sense and be approved by the GM.
The target can either accept the proposed effect or resolve the attack as normal.
It isn't possible to react if the effect is accepted.


== Non-lethal attacks

Non-lethal attacks don't inflict damage but instead force the target to pass a save or suffer negative consequences.
They can be dodged and countered and can be used to counter.
Since they inflict no damage they are always resolved last in case of a counter.

* *Disarm*.
A nearby target must pass a STR save or drop a weapon chosen by the attacker.

* *Grapple*.
A nearby target must pass a STR save or be grabbed by the attacker.
Grabbed characters are _entangled_ for as long as their enemy keeps hold of them.
Characters who are grabbing another character can move together with them and attack them while keeping hold, but doing anything else automatically frees the grabbed character.
They can also shove the grabbed character, freeing them but forcing them to move by half a zone and/or pushing them into a hazard in their zone.


== Sneaking in combat

Characters who launch an ambush are concealed at the start of the fight.
Hiding later during the fight requires being out of sight for a while or a major distraction.
The GM should keep the position of concealed characters hidden from the Players, and should control characters that they realistically ignore concealed Player characters.

Concealed characters are revealed when they make noise or become visible to the enemy.
Actions which might reveal a character include: attacking, invoking a power, talking, moving without sneaking, walking right in front of the enemy, etc.

Characters who are concealed at the start of the fight can take a bonus turn before the others.
Follow the normal round procedure, but characters who aren't concealed and are unaware of the concealed characters can't take their turn.
Characters attacked by concealed enemies are taken by surprise and can't react.


== Morale

Groups must make a morale check after being reduced to half or less their original number during a fight.
Characters fighting alone must do so after taking damage reducing their health to half or less the maximum.
Morale checks are made at the end of the round, during the morale phase.

Make a group WIT save: those who fail must surrender or retreat, but those who pass aren't subject to morale for the remainder of the stretch.
Characters who are immune to fear are also immune to morale.


== Surrendering

Characters can spend their turn to surrender, throwing their weapons away, putting their hands up, etc.
Their turn is wasted, but they might be spared by the enemy.
Surrendering characters who are harmed by the enemy can resume fighting normally even if they previously failed a morale check.


== Chases

Short chases can be played out using the combat rules.
Chases over long distances can be resolved with the fleeing character making a group AGI save: those who pass escape, those who fail are reached by the pursuers.
If the fleeing characters can move faster or keep the speed for longer, the save is not required.
If the opposite is true, escaping is impossible.


== Optional rule: fast and slow activations

You can use this optional rule if you would like WIT to influence the order in which characters act during the round and you don't mind a little bit of extra complexity.

At the beginning of each round, right after the initiative phase, the GM openly rolls a d20.
The result is the fast action threshold.
You can leave the d20 on the table as a reminder of this value.

The action phase is divided in two sub-phases: fast and slow.
Each sub-phase follows the normal action phase rules, with the following additions:

* During the fast action sub-phase, only characters whose WIT matches or exceeds the fast action threshold can take their turn.
As an exception, on the first round only, characters who initiated the fight or were prepared for it can always take their turn, no matter what their WIT is.

* During the slow action sub-phase, the characters who haven't taken their turn yet can now do so.
This includes both characters who couldn't take action during the fast action sub-phase, and those who didn't due to early passing.

Characters can always react in any sub-phase, no matter what their WIT score is.

++++
{{% details title="Example" closed="true" %}}

Balthasar (WIT 12), Sybilla (WIT 6), and Theobald (WIT 9) are fighting against two bandits (WIT 8) and their leader (WIT 10);
The Players have the initiative.

The GM rolls a d20 to determine the fast action threshold: the result is 9.
During the fast action sub-phase, only Balthasar, Theobald, and the bandit leader can act.
Sybilla and the two bandits can't, because their WIT is lower than 9.

The fast action sub-phase begins.
Since the Players have the initiative, they take turn first.
They choose Theobald to go first: he decides to attack one of the two bandits.
The bandit chooses to react to the attack by dodging: they can do so even if they can't take turn during the fast action phase because reactions are always allowed.
After the attack is resolved, it's the enemies' turn and the bandit leader acts.
Balthasar could then act, but the Players decide to pass instead.
The bandits must pass because they have no characters left who can act, and the sub-phase ends.

The slow action sub-phase begins.
All characters who haven't acted yet can take a turn: Balthasar, Sybilla, and one of the bandits, the one who didn't react to the attack.
The Players again start because they have the initiative.
Sybilla goes first, followed by the bandit, and ending with Balthasar.
Both factions must pass because they have no characters left, and the action phase ends.

{{% /details %}}
++++


== Optional rule: the chaos of combat

These is an optional rule you can use to represent the chaotic nature of combat and to reduce the amount of time spent to resolve fights if the Players like to strategise and think a lot.
If you prefer a more '`relaxed`' and tactical experience, feel free to ignore them.

* The Players aren't allowed to speak to each other unless their character spends a bonus action to say a short sentence.

* Each Player has 15 seconds to declare what they intend to do on their turn, otherwise they do nothing.
This doesn't include the time required to actually resolve the actions, take all the time you need for that.
