---
title: Rest & Recovery
weight: 60
prev: /docs/omens
next: /docs/character_keywords
---
:toc:

== Day rests

Characters can spend a watch to take a day rest.
When doing so they must eat, drink, and sleep.
Characters who satisfy all needs recover health to the maximum.
Those who don't recover no health and temporarily reduce an ability by 1 for each unsatisfied need: STR if they didn't eat, AGI if they didn't drink, and WIT if they didn't sleep.

In a settlement it is possible to pay 4ʂ for lodging, which includes food, drinks, and a bed.
In the wilderness it is necessary to consume a _ration_ to eat, consume a unit _water_ to drink (unless there is plenty of drinkable water in the area), and have a _camping kit_ to sleep.
Animals don't need a _camping kit_, and they don't need a _ration_ or a _drink_ while in their natural habitat as they can forage for themselves.

After two watches spent doing something else, characters must take a day rest or temporarily reduce all abilities by 1.
On the fourth watch they are forced to take a day rest.


== Full rests

Characters can spend a week in a settlement to take a full rest.
It costs 64ʂ to pay for lodging, healing, and entertainment.
They recover health to the maximum, restore omens to the maximum, remove all conditions (including many injuries which can't be get rid of otherwise), and restore temporarily reduced abilities to their original score.


== Foraging

Characters can spend a watch looking for food in the wilderness.
They roll on the <<tb_foraging>> table to see if they find something edible.
_Rations_ gathered in this way are perishable and are discarded if not consumed before the next day rest.

.Foraging
[[tb_foraging]]
[options='header, unbreakable', cols="^1,<14"]
|===
|D8 |Foraging result

|1 |*Fruits and vegetables*.
You find a _ration_ unless you are in a desolate environment.

|2 |*Dubious mushrooms*.
You find a _ration_ unless you are in a desolate environment, but you aren't sure if it's edible.
If consumed there is a 1:4 chance that it makes the person sick: they temporarily reduce all abilities by 1.

|3-4 |*Fish*.
You find a _ration_ if you have a _fishing kit_ and there is a body of water in or neighbouring your region.

|5-6 |*Small game*.
You find a _ration_ if you have a _trapping kit_ and you aren't in a desolate environment.

|7 |*Big game*.
Unless you are in a desolate environment, you find 4 _rations_ if you pass a WIT save to track a prey and then roll 4 or more damage with a ranged attack to kill it.

|8 |*Nothing*.
You come back empty handed.

|===
