= Welcome to Murdham
:nofooter:
:stylesheet: ./css/murdham.css
:linkcss:

include::../description.adoc[]


== Game material

* xref:rulebook/murdham.adoc[*The rules*]: read them before playing, and use them as reference during the game.

* link:assets/character_sheet_a4.pdf[*The character sheet*]: print one for each Player.


== Game features

* *Deadly adventures*: death is behind the corner at every moment.
Characters are normal people, not heroes, and every fight could be their last.
Both inside and outside combat, the Players must use their ingenuity and take advantage of their skills and gear to reduce risks to the minimum.

* *Streamlined rules*: no need to study huge tome of rules, memorise monster profiles taking whole pages, or reference the rulebook constantly.

* *Fast action resolution*: just roll a d20 under an ability score.
No modifiers, no dice pools, no advantage-disadvantage mechanics: everyone always knows clearly what is needed to succeed!
Difficulty comes in three steps: trivial (no roll, you just do it), challenging (roll), impossible (no roll, you can't do it).

* *Skill-based character development*: skills are keywords, a character either has them or they don't.
They provide significant advantages, such as the ability to succeed in certain actions without rolling, to inflict more damage with weapons, to cast spells, and so on.

* *Slot-based inventory*: characters can carry a limited amount of gear, tracked with a slot-based inventory system requiring very little math and book-keeping.

* *Simple yet deep combat rules*: factions alternate activating their fighters.
A single roll is made for everyone to determine who can move faster than others.
Attacks always hit unless performed under very challenging circumstances.
Characters can act out of turn order with a reaction mechanic, used for example to attempt to dodge attack, counter, or intercept moving enemies.

* *Corruption system*: using magic or being exposed to dark otherwordly powers inflicts corruption.
Each time this happens, the character might suffer damage and even mutate in horrifying ways.

* *Vile sorcery*: sorcerers can spend mana to invoke sorcerous powers safely, but can also push themselves at the risk of a miscast and corruption.
Every spell can be enhanced to improve its range, duration, and effect.
Sacred powers are safer than sorcerous powers, but can be invoked more rarely.
Characters who have been tainted by corruption run the risk of their prayers not being answered.

* *Complete rules*: the rules provide concise guidelines on how to handle most of the common situations found in a fantasy adventure game.
It isn't just a set of basic mechanics left for the GM to completely figure out.
